create table COMBINATIONS (COMBINATION VARCHAR(255));

create table KEYMAPPING (KEY INT, MAPPING VARCHAR(5));



insert into KEYMAPPING (KEY , MAPPING) VALUES (0, '0');
insert into KEYMAPPING (KEY , MAPPING) VALUES (1, '1');
insert into KEYMAPPING (KEY , MAPPING) VALUES (2, '2ABC');
insert into KEYMAPPING (KEY , MAPPING) VALUES (3, '3DEF');
insert into KEYMAPPING (KEY , MAPPING) VALUES (4, '4GHI');
insert into KEYMAPPING (KEY , MAPPING) VALUES (5, '5JKL');
insert into KEYMAPPING (KEY , MAPPING) VALUES (6, '6MNO');
insert into KEYMAPPING (KEY , MAPPING) VALUES (7, '7PQRS');
insert into KEYMAPPING (KEY , MAPPING) VALUES (8, '8TUV');
insert into KEYMAPPING (KEY , MAPPING) VALUES (9, '9WXYZ');


